server:
  port: 10000
spring:
  application:
    name: rewards-api
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-example.auth0.com/}
          audiences: ${AUTH0_AUDIENCE:https://rewards-api.xamos.org}
  # Disable docker compose plugin and database initialization by default
  docker:
    compose:
      lifecycle-management: none
  sql:
    init:
      mode: never
  profiles:
    group:
      dev: local
      unit: test
      integration: test
app:
  security:
    auth0:
      domain: ${AUTH0_DOMAIN}
      management:
        client-id: ${AUTH0_MANAGEMENT_CLIENT_ID}
        client-secret: ${AUTH0_MANAGEMENT_CLIENT_SECRET}
    permitted-paths:
      - /actuator/**
    cors:
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - Authorization
        - Content-Type
        - X-App-Identity
      exposed-headers:
        - Authorization
        - X-App-Identity
      allow-credentials: true
#logging:
#  level:
#    root: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      lifecycle-management: start-and-stop
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      platform: postgres # Needed to inform Spring to look at schema-postgres.sql
app:
  security:
    cors:
      allowed-origins:
        - http://localhost:4200
---
# Global test configuration (all tests)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      platform: h2 # Needed to inform Spring to look at schema-h2.sql
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
app:
  security:
    auth0:
      domain: dev-example.auth0.com
      management:
        client-id: mock-id
        client-secret: mock-secret
    cors:
      allowed-origins:
        - http://localhost:4200
    permitted-paths:
      - /actuator/**
---
# Unit test specific configuration
spring:
  config:
    activate:
      on-profile: unit
---
# Integration test specific configuration
spring:
  config:
    activate:
      on-profile: integration
app:
  security:
    permitted-paths:
      - /actuator/**
      - /internal/**
