server:
  port: 10000
spring:
  application:
    name: rewards-api
  threads:
    virtual:
      enabled: true
  # Disable docker compose plugin and database initialization by default
  docker:
    compose:
      lifecycle-management: none
  sql:
    init:
      mode: never
  profiles:
    group:
      dev: local
      unit: test
      integration: test
#logging:
#  level:
#    root: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      lifecycle-management: start-and-stop
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      platform: postgres # Needed to inform Spring to look at schema-postgres.sql
---
# Global test configuration (all tests)
spring:
  config:
    activate:
      on-profile: test
---
# Unit test specific configuration
spring:
  config:
    activate:
      on-profile: unit
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      platform: h2 # Needed to inform Spring to look at schema-h2.sql
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
---
# Integration test specific configuration
spring:
  config:
    activate:
      on-profile: integration
